spring:
  profiles:
    active: dev
    include: secret
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId:
            # 내가 받을 정보
            scope: account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            # 카카오 개발자에 등록된 redirect-uri
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

datasource:
  username: root
  url: jdbc:mariadb://127.0.0.1::3306/world?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
  driverClassName: org.mariadb.jdbc.Driver
  password:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  root:
    path: /home/user/file
  resource:
    path: file:/home/uesr/file/
  request:
    path: /file/**
  origin:
    path: /file/

custom:
  genFileDirPath: /home/user/file/notice